<?php

use Illuminate\Database\Seeder;

class ShowsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shows')->insert([
            [
                'show_id' => '4',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/1 16:00:00',
                'end_datetime' => '2019/11/1 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '5',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/1 10:15:00',
                'end_datetime' => '2019/11/1 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '6',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/1 11:00:00',
                'end_datetime' => '2019/11/1 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '7',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/1 15:00:00',
                'end_datetime' => '2019/11/1 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '8',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/2 16:00:00',
                'end_datetime' => '2019/11/2 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '9',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/2 10:15:00',
                'end_datetime' => '2019/11/2 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '10',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/2 11:00:00',
                'end_datetime' => '2019/11/2 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '11',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/2 15:00:00',
                'end_datetime' => '2019/11/2 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '12',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/3 16:00:00',
                'end_datetime' => '2019/11/3 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '13',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/3 10:15:00',
                'end_datetime' => '2019/11/3 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '14',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/3 11:00:00',
                'end_datetime' => '2019/11/3 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '15',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/3 15:00:00',
                'end_datetime' => '2019/11/3 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '16',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/4 16:00:00',
                'end_datetime' => '2019/11/4 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '17',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/4 10:15:00',
                'end_datetime' => '2019/11/4 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '18',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/4 11:00:00',
                'end_datetime' => '2019/11/4 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '19',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/4 15:00:00',
                'end_datetime' => '2019/11/4 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '20',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/5 16:00:00',
                'end_datetime' => '2019/11/5 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '21',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/5 10:15:00',
                'end_datetime' => '2019/11/5 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '22',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/5 11:00:00',
                'end_datetime' => '2019/11/5 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '23',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/5 15:00:00',
                'end_datetime' => '2019/11/5 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '24',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/6 16:00:00',
                'end_datetime' => '2019/11/6 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '25',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/6 10:15:00',
                'end_datetime' => '2019/11/6 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '26',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/6 11:00:00',
                'end_datetime' => '2019/11/6 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '27',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/6 15:00:00',
                'end_datetime' => '2019/11/6 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '28',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/7 16:00:00',
                'end_datetime' => '2019/11/7 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '29',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/7 10:15:00',
                'end_datetime' => '2019/11/7 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '30',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/7 11:00:00',
                'end_datetime' => '2019/11/7 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '31',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/7 15:00:00',
                'end_datetime' => '2019/11/7 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '32',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/8 16:00:00',
                'end_datetime' => '2019/11/8 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '33',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/8 10:15:00',
                'end_datetime' => '2019/11/8 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '34',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/8 11:00:00',
                'end_datetime' => '2019/11/8 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '35',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/8 15:00:00',
                'end_datetime' => '2019/11/8 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '36',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/9 16:00:00',
                'end_datetime' => '2019/11/9 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '37',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/9 10:15:00',
                'end_datetime' => '2019/11/9 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '38',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/9 11:00:00',
                'end_datetime' => '2019/11/9 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '39',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/9 15:00:00',
                'end_datetime' => '2019/11/9 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '40',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/10 16:00:00',
                'end_datetime' => '2019/11/10 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '41',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/10 10:15:00',
                'end_datetime' => '2019/11/10 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '42',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/10 11:00:00',
                'end_datetime' => '2019/11/10 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '43',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/10 15:00:00',
                'end_datetime' => '2019/11/10 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '44',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/11 16:00:00',
                'end_datetime' => '2019/11/11 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '45',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/11 10:15:00',
                'end_datetime' => '2019/11/11 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '46',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/11 11:00:00',
                'end_datetime' => '2019/11/11 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '47',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/11 15:00:00',
                'end_datetime' => '2019/11/11 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '48',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/12 16:00:00',
                'end_datetime' => '2019/11/12 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '49',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/12 10:15:00',
                'end_datetime' => '2019/11/12 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '50',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/12 11:00:00',
                'end_datetime' => '2019/11/12 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '51',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/12 15:00:00',
                'end_datetime' => '2019/11/12 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '52',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/13 16:00:00',
                'end_datetime' => '2019/11/13 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '53',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/13 10:15:00',
                'end_datetime' => '2019/11/13 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '54',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/13 11:00:00',
                'end_datetime' => '2019/11/13 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '55',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/13 15:00:00',
                'end_datetime' => '2019/11/13 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '56',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/14 16:00:00',
                'end_datetime' => '2019/11/14 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '57',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/14 10:15:00',
                'end_datetime' => '2019/11/14 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '58',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/14 11:00:00',
                'end_datetime' => '2019/11/14 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '59',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/14 15:00:00',
                'end_datetime' => '2019/11/14 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '60',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/15 16:00:00',
                'end_datetime' => '2019/11/15 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '61',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/15 10:15:00',
                'end_datetime' => '2019/11/15 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '62',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/15 11:00:00',
                'end_datetime' => '2019/11/15 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '63',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/15 15:00:00',
                'end_datetime' => '2019/11/15 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '64',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/16 16:00:00',
                'end_datetime' => '2019/11/16 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '65',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/16 10:15:00',
                'end_datetime' => '2019/11/16 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '66',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/16 11:00:00',
                'end_datetime' => '2019/11/16 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '67',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/16 15:00:00',
                'end_datetime' => '2019/11/16 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '68',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/17 16:00:00',
                'end_datetime' => '2019/11/17 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '69',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/17 10:15:00',
                'end_datetime' => '2019/11/17 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '70',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/17 11:00:00',
                'end_datetime' => '2019/11/17 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '71',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/17 15:00:00',
                'end_datetime' => '2019/11/17 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '72',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/18 16:00:00',
                'end_datetime' => '2019/11/18 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '73',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/18 10:15:00',
                'end_datetime' => '2019/11/18 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '74',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/18 11:00:00',
                'end_datetime' => '2019/11/18 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '75',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/18 15:00:00',
                'end_datetime' => '2019/11/18 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '76',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/19 16:00:00',
                'end_datetime' => '2019/11/19 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '77',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/19 10:15:00',
                'end_datetime' => '2019/11/19 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '78',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/19 11:00:00',
                'end_datetime' => '2019/11/19 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '79',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/19 15:00:00',
                'end_datetime' => '2019/11/19 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '80',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/20 16:00:00',
                'end_datetime' => '2019/11/20 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '81',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/20 10:15:00',
                'end_datetime' => '2019/11/20 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '82',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/20 11:00:00',
                'end_datetime' => '2019/11/20 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '83',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/20 15:00:00',
                'end_datetime' => '2019/11/20 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '84',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/21 16:00:00',
                'end_datetime' => '2019/11/21 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '85',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/21 10:15:00',
                'end_datetime' => '2019/11/21 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '86',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/21 11:00:00',
                'end_datetime' => '2019/11/21 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '87',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/21 15:00:00',
                'end_datetime' => '2019/11/21 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '88',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/22 16:00:00',
                'end_datetime' => '2019/11/22 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '89',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/22 10:15:00',
                'end_datetime' => '2019/11/22 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '90',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/22 11:00:00',
                'end_datetime' => '2019/11/22 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '91',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/22 15:00:00',
                'end_datetime' => '2019/11/22 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '92',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/23 16:00:00',
                'end_datetime' => '2019/11/23 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '93',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/23 10:15:00',
                'end_datetime' => '2019/11/23 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '94',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/23 11:00:00',
                'end_datetime' => '2019/11/23 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '95',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/23 15:00:00',
                'end_datetime' => '2019/11/23 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '96',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/24 16:00:00',
                'end_datetime' => '2019/11/24 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '97',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/24 10:15:00',
                'end_datetime' => '2019/11/24 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '98',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/24 11:00:00',
                'end_datetime' => '2019/11/24 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '99',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/24 15:00:00',
                'end_datetime' => '2019/11/24 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '100',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/25 16:00:00',
                'end_datetime' => '2019/11/25 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '101',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/25 10:15:00',
                'end_datetime' => '2019/11/25 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '102',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/25 11:00:00',
                'end_datetime' => '2019/11/25 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '103',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/25 15:00:00',
                'end_datetime' => '2019/11/25 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '104',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/26 16:00:00',
                'end_datetime' => '2019/11/26 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '105',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/26 10:15:00',
                'end_datetime' => '2019/11/26 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '106',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/26 11:00:00',
                'end_datetime' => '2019/11/26 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '107',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/26 15:00:00',
                'end_datetime' => '2019/11/26 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '108',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/27 16:00:00',
                'end_datetime' => '2019/11/27 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '109',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/27 10:15:00',
                'end_datetime' => '2019/11/27 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '110',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/27 11:00:00',
                'end_datetime' => '2019/11/27 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '111',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/27 15:00:00',
                'end_datetime' => '2019/11/27 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '112',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/28 16:00:00',
                'end_datetime' => '2019/11/28 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '113',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/28 10:15:00',
                'end_datetime' => '2019/11/28 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '114',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/28 11:00:00',
                'end_datetime' => '2019/11/28 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '115',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/28 15:00:00',
                'end_datetime' => '2019/11/28 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '116',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/29 16:00:00',
                'end_datetime' => '2019/11/29 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '117',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/29 10:15:00',
                'end_datetime' => '2019/11/29 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '118',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/29 11:00:00',
                'end_datetime' => '2019/11/29 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '119',
                'screen_symbol' => '1',
                'start_datetime' => '2019/11/29 15:00:00',
                'end_datetime' => '2019/11/29 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '120',
                'screen_symbol' => '0',
                'start_datetime' => '2019/11/30 16:00:00',
                'end_datetime' => '2019/11/30 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '124',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/1 16:00:00',
                'end_datetime' => '2019/12/1 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '125',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/1 10:15:00',
                'end_datetime' => '2019/12/1 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '126',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/1 11:00:00',
                'end_datetime' => '2019/12/1 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '127',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/1 15:00:00',
                'end_datetime' => '2019/12/1 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '128',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/2 16:00:00',
                'end_datetime' => '2019/12/2 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '129',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/2 10:15:00',
                'end_datetime' => '2019/12/2 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '130',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/2 11:00:00',
                'end_datetime' => '2019/12/2 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '131',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/2 15:00:00',
                'end_datetime' => '2019/12/2 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '132',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/3 16:00:00',
                'end_datetime' => '2019/12/3 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '133',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/3 10:15:00',
                'end_datetime' => '2019/12/3 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '134',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/3 11:00:00',
                'end_datetime' => '2019/12/3 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '135',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/3 15:00:00',
                'end_datetime' => '2019/12/3 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '136',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/4 16:00:00',
                'end_datetime' => '2019/12/4 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '137',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/4 10:15:00',
                'end_datetime' => '2019/12/4 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '138',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/4 11:00:00',
                'end_datetime' => '2019/12/4 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '139',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/4 15:00:00',
                'end_datetime' => '2019/12/4 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '140',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/5 16:00:00',
                'end_datetime' => '2019/12/5 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '141',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/5 10:15:00',
                'end_datetime' => '2019/12/5 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '142',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/5 11:00:00',
                'end_datetime' => '2019/12/5 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '143',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/5 15:00:00',
                'end_datetime' => '2019/12/5 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '144',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/6 16:00:00',
                'end_datetime' => '2019/12/6 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '145',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/6 10:15:00',
                'end_datetime' => '2019/12/6 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '146',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/6 11:00:00',
                'end_datetime' => '2019/12/6 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '147',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/6 15:00:00',
                'end_datetime' => '2019/12/6 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '148',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/7 16:00:00',
                'end_datetime' => '2019/12/7 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '149',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/7 10:15:00',
                'end_datetime' => '2019/12/7 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '150',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/7 11:00:00',
                'end_datetime' => '2019/12/7 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '151',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/7 15:00:00',
                'end_datetime' => '2019/12/7 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '152',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/8 16:00:00',
                'end_datetime' => '2019/12/8 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '153',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/8 10:15:00',
                'end_datetime' => '2019/12/8 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '154',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/8 11:00:00',
                'end_datetime' => '2019/12/8 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '155',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/8 15:00:00',
                'end_datetime' => '2019/12/8 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '156',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/9 16:00:00',
                'end_datetime' => '2019/12/9 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '157',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/9 10:15:00',
                'end_datetime' => '2019/12/9 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '158',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/9 11:00:00',
                'end_datetime' => '2019/12/9 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '159',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/9 15:00:00',
                'end_datetime' => '2019/12/9 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '160',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/10 16:00:00',
                'end_datetime' => '2019/12/10 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '161',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/10 10:15:00',
                'end_datetime' => '2019/12/10 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '162',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/10 11:00:00',
                'end_datetime' => '2019/12/10 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '163',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/10 15:00:00',
                'end_datetime' => '2019/12/10 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '164',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/11 16:00:00',
                'end_datetime' => '2019/12/11 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '165',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/11 10:15:00',
                'end_datetime' => '2019/12/11 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '166',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/11 11:00:00',
                'end_datetime' => '2019/12/11 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '167',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/11 15:00:00',
                'end_datetime' => '2019/12/11 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '168',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/12 16:00:00',
                'end_datetime' => '2019/12/12 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '169',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/12 10:15:00',
                'end_datetime' => '2019/12/12 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '170',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/12 11:00:00',
                'end_datetime' => '2019/12/12 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '171',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/12 15:00:00',
                'end_datetime' => '2019/12/12 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '172',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/13 16:00:00',
                'end_datetime' => '2019/12/13 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '173',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/13 10:15:00',
                'end_datetime' => '2019/12/13 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '174',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/13 11:00:00',
                'end_datetime' => '2019/12/13 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '175',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/13 15:00:00',
                'end_datetime' => '2019/12/13 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '176',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/14 16:00:00',
                'end_datetime' => '2019/12/14 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '177',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/14 10:15:00',
                'end_datetime' => '2019/12/14 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '178',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/14 11:00:00',
                'end_datetime' => '2019/12/14 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '179',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/14 15:00:00',
                'end_datetime' => '2019/12/14 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '180',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/15 16:00:00',
                'end_datetime' => '2019/12/15 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '181',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/15 10:15:00',
                'end_datetime' => '2019/12/15 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '182',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/15 11:00:00',
                'end_datetime' => '2019/12/15 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '183',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/15 15:00:00',
                'end_datetime' => '2019/12/15 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '184',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/16 16:00:00',
                'end_datetime' => '2019/12/16 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '185',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/16 10:15:00',
                'end_datetime' => '2019/12/16 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '186',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/16 11:00:00',
                'end_datetime' => '2019/12/16 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '187',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/16 15:00:00',
                'end_datetime' => '2019/12/16 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '188',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/17 16:00:00',
                'end_datetime' => '2019/12/17 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '189',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/17 10:15:00',
                'end_datetime' => '2019/12/17 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '190',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/17 11:00:00',
                'end_datetime' => '2019/12/17 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '191',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/17 15:00:00',
                'end_datetime' => '2019/12/17 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '192',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/18 16:00:00',
                'end_datetime' => '2019/12/18 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '193',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/18 10:15:00',
                'end_datetime' => '2019/12/18 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '194',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/18 11:00:00',
                'end_datetime' => '2019/12/18 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '195',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/18 15:00:00',
                'end_datetime' => '2019/12/18 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '196',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/19 16:00:00',
                'end_datetime' => '2019/12/19 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '197',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/19 10:15:00',
                'end_datetime' => '2019/12/19 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '198',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/19 11:00:00',
                'end_datetime' => '2019/12/19 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '199',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/19 15:00:00',
                'end_datetime' => '2019/12/19 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '200',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/20 16:00:00',
                'end_datetime' => '2019/12/20 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '201',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/20 10:15:00',
                'end_datetime' => '2019/12/20 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '202',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/20 11:00:00',
                'end_datetime' => '2019/12/20 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '203',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/20 15:00:00',
                'end_datetime' => '2019/12/20 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '204',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/21 16:00:00',
                'end_datetime' => '2019/12/21 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '205',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/21 10:15:00',
                'end_datetime' => '2019/12/21 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '206',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/21 11:00:00',
                'end_datetime' => '2019/12/21 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '207',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/21 15:00:00',
                'end_datetime' => '2019/12/21 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '208',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/22 16:00:00',
                'end_datetime' => '2019/12/22 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '209',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/22 10:15:00',
                'end_datetime' => '2019/12/22 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '210',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/22 11:00:00',
                'end_datetime' => '2019/12/22 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '211',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/22 15:00:00',
                'end_datetime' => '2019/12/22 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '212',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/23 16:00:00',
                'end_datetime' => '2019/12/23 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '213',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/23 10:15:00',
                'end_datetime' => '2019/12/23 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '214',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/23 11:00:00',
                'end_datetime' => '2019/12/23 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '215',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/23 15:00:00',
                'end_datetime' => '2019/12/23 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '216',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/24 16:00:00',
                'end_datetime' => '2019/12/24 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '217',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/24 10:15:00',
                'end_datetime' => '2019/12/24 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '218',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/24 11:00:00',
                'end_datetime' => '2019/12/24 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '219',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/24 15:00:00',
                'end_datetime' => '2019/12/24 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '220',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/25 16:00:00',
                'end_datetime' => '2019/12/25 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '221',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/25 10:15:00',
                'end_datetime' => '2019/12/25 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '222',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/25 11:00:00',
                'end_datetime' => '2019/12/25 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '223',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/25 15:00:00',
                'end_datetime' => '2019/12/25 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '224',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/26 16:00:00',
                'end_datetime' => '2019/12/26 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '225',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/26 10:15:00',
                'end_datetime' => '2019/12/26 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '226',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/26 11:00:00',
                'end_datetime' => '2019/12/26 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '227',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/26 15:00:00',
                'end_datetime' => '2019/12/26 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '228',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/27 16:00:00',
                'end_datetime' => '2019/12/27 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '229',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/27 10:15:00',
                'end_datetime' => '2019/12/27 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '230',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/27 11:00:00',
                'end_datetime' => '2019/12/27 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '231',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/27 15:00:00',
                'end_datetime' => '2019/12/27 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '232',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/28 16:00:00',
                'end_datetime' => '2019/12/28 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '233',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/28 10:15:00',
                'end_datetime' => '2019/12/28 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '234',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/28 11:00:00',
                'end_datetime' => '2019/12/28 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '235',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/28 15:00:00',
                'end_datetime' => '2019/12/28 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '236',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/29 16:00:00',
                'end_datetime' => '2019/12/29 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '237',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/29 10:15:00',
                'end_datetime' => '2019/12/29 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '238',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/29 11:00:00',
                'end_datetime' => '2019/12/29 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '239',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/29 15:00:00',
                'end_datetime' => '2019/12/29 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '240',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/30 16:00:00',
                'end_datetime' => '2019/12/30 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '241',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/30 10:15:00',
                'end_datetime' => '2019/12/30 14:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '242',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/30 11:00:00',
                'end_datetime' => '2019/12/30 15:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '2',
                'admin_id' => '1',
            ],
            [
                'show_id' => '243',
                'screen_symbol' => '1',
                'start_datetime' => '2019/12/30 15:00:00',
                'end_datetime' => '2019/12/30 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
            [
                'show_id' => '244',
                'screen_symbol' => '0',
                'start_datetime' => '2019/12/31 16:00:00',
                'end_datetime' => '2019/12/31 17:00:00',
                'cleaning_time' => '15',
                'status' => '1',
                'movie_id' => '1',
                'admin_id' => '1',
            ],
        ]);
    }
}
